### ISSUE TITLE
QoL improvement: Detect if a stack is present on previews when adding deployment settings

### ISSUE THREAD

**Issue by sicarul** [pulumi/pulumi-pulumiservice#224]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

When adding a new deployment setting if the stack does not exist yet, the preview finishes fine, but the update fails:

```error: failed to create deployment settings for stack (<stack_name>): 404 API error: Not Found: Stack '<stack_name>' not found```

It'd be nice to detect it directly during preview, so in a PR we can quickly detect it and avoid pushing it without a matching stack

### Affected area/feature

Deployment settings

**Comment by IaroslavTitov** [comment]
I think this is a good idea, but unfrotunately I think it wouldn't work due to the fact that PSP allows you to create Stacks as resources. So it is entirely possible that during the preview stack doesn't exist, but during the update it does, created as part of the update. PSP also allows you to configure DS on the same stacks that has the DS resource in it. 

I don't think there's any way to check that during Check method, so sadly can't do it. You can always create a Stack resource and pass its name into DS to make sure it exists.
