### ISSUE TITLE
Environment YAML always shows changes on pulumi refresh

### ISSUE THREAD

**Issue by OriolOMM** [pulumi/pulumi-pulumiservice#367]
### What happened?

Hi,

Using Environment resources I always receive diffs when doing pulumi refresh.

### Example

By having this typescript code:

```
const envFileContent = fs.readFileSync(`environments/${envFile}`, 'utf8');
    const envName = envFile.split('.')[0];
    new pulumiservice.Environment(envName, {
      name: envName,
      organization: 'sss',
      yaml: new pulumi.asset.StringAsset(envFileContent),
    });
```

And this YAML file:

```
values:
  azure:
    tenantid: 0000-0000-00000-00000-00000
  pulumiConfig:
    azure-native:tenantId: ${azure.tenantid}
    pulumi:tags:
      cloud-provider: azure
```

If I do a pulumi up, and then pulumi refresh I receive:

~ pulumiservice:index:Environment: (update)
        [id=sss/azure-sandbox]
        [urn=urn:pulumi:prod::pulumi-cloud::pulumiservice:index:Environment::azure]
        [provider=urn:pulumi:prod::pulumi-cloud::pulumi:providers:pulumiservice::default_0_23_0::c130c479-0e68-4078-ad3e-222222222222]
      ~ yaml: [secret] => [secret]

### Output of `pulumi about`

at 18:39:44 ❯ pulumi about  
CLI          
Version      3.122.0
Go Version   go1.22.4
Go Compiler  gc

Plugins
KIND      NAME    VERSION
language  nodejs  unknown

Host     
OS       debian
Version  12.6
Arch     aarch64

This project is written in nodejs: executable='/usr/local/bin/node' version='v20.15.0'

Backend        
Name           pulumi.com
Token type     personal

Pulumi locates its logs in /tmp by default
warning: Failed to get information about the Pulumi program's dependencies: could not find either /workspaces/pulumi/projects/pulumi-cloud/yarn.lock or /workspaces/pulumi/projects/pulumi-cloud/package-lock.json

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by IaroslavTitov** [comment]
Hello there, thank you for filing this issue. This happens due to auto-formatting that ESC does upon creation/update of an environment.

Today, it is possible to have environments without constant diff, but that requires a very particular format and spacing of the text inside the file or string. Feel free to checkout our examples for this in `examples` folder. 

Of course, that is not *really* a solution, so we are tracking this issue internally as well and have an idea for addressing this. I am scheduled to work on this issue within this month, but sadly I can't guarantee any deadlines.
